spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.196:6226/userdb?characterEncoding=utf8
    username: root
    password: root123
  zipkin:
    base-url: http://192.168.0.189:9500
    sender:
      type: web
  sleuth:
    sampler:
      #request采样的数量 默认是0.1 也即是10%，即采样10%的请求数据；
      #因为在分布式系统中，数据量可能会非常大，因此采样非常重要我们示例数据少最好配置为1全采样，100%的采集会稍微影响一点性能
      probability: 1.0
server:
  port: 9092
eureka:
  client:
    enable: true
    #是否可以被发现
    register-with-eureka: true
    #是否从eureka 读取注册的应用实例
    fetch-registry: true
    region: local
    availability-zones:
      local: local-zone1,local-zone2
    service-url:
      local-zone1: http://localhost:8081/eureka/
      local-zone2: http://localhost:8082/eureka/
    instance:
      instance-id: ${spring.application.name}:${server.port}

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-packag: self.study.spring.cloud.common.model
  configuration:
    map-underscore-to-camel-case: true

